apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jeeprep-app
  labels:
    app: guestbook
    tier: Full-Stack
spec:
  
  replicas: 3
  selector:
    matchLabels:
      tier: jeeprep
  template:
    metadata:
      labels:
        tier: jeeprep
    spec:
      containers:
      - name: jeeprep
        image: adarshs2023/jeeprep:latest
        ports:
        - containerPort: 8080
