# Generated by Django 5.2.8 on 2025-11-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField()),
                ("number", models.IntegerField()),
                ("time", models.IntegerField()),
                ("difficulty", models.CharField(max_length=20)),
                ("is_negative", models.BooleanField()),
                ("topics", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
